### ISSUE TITLE
Please help me develop a two factor auth app

### ISSUE THREAD

**Issue by Muzosh** [nursoda/twofactor_email#253]
Hello, I'm trying to develop a very simple two factor auth app into Nextcloud.
At first, I just want a simple PHP code to do the authentication.

Here is a link for my Nextcloud Forums post, where I provide more information about my struggle: [link](https://help.nextcloud.com/t/please-help-me-develop-a-two-factor-provider/127729).

Basically I just need a bare bone minimal code-base for a such and app. Could you please help me?

**Comment by nursoda** [comment]
Sorry I didn't see your request, my GitHub notifications were misconfigured.

Concerning your request, I'm most probably the wrong guy to ask: I'm struggling myself to understand this app in full. Currently, I maintain it as good as I can since the original dev didn't have any time, even to update dependencies and versions. So, I'll look into your forum post and would be delighted to profit from your insights published there.
