### ISSUE TITLE
No submit icon in verification dialog (regression)

### ISSUE THREAD

**Issue by wokawoka** [nursoda/twofactor_email#262]
Hello,
today I updated the app to the latest version 2.1.1 and I've immediately noticed that the submit button is no more appearing (see screenshot below) .
I can login by filling in the code and followed by pressing the enter key but most of my users are stuck and can´t log in to nextcloud.
When I upgraded the app I was initially running nextcloud 21.03, now I've upgraded to the last 22.2.3 hoping that it could fix the problem but nothing changed. 
I removed all my css cutomizations, I'm not running any other exotic app. 
Do you by chance have a suggestion or an  idea about how I could fix this problem?
Thank you!

![Screenshot_20211218_041437](https://user-images.githubusercontent.com/7824587/146627306-f1b07a19-c7a3-4d82-bba9-60334aa1c7a2.png)

**Comment by wokawoka** [comment]
I manually reverted back to 2.0.1 and everything is back to normal.
![Screenshot_20211218_130950](https://user-images.githubusercontent.com/7824587/146643370-bddfdfb7-317f-411c-b2a9-e1e5690cc707.png)
I've also noticed that with version 2.1.1 the mail icon is much bigger than the 2fa otp icon, which is not the best from the aesthetic standpoint.
For now I will try to stay on 2.0.1 . 
I'm I really the only one experiencing this problem?
Thank you!

**Comment by ddan39** [comment]
It looks like this is on purpose, but I disagree with the change.

Almost every person the first time they use this has come to me asking how they login because there is no button to press.

This is also a bigger issue when using the mobile app because hitting Enter on mobile isn't as natural as on a PC. You have to click back into the field then hit Return on the virtual keyboard.

You can see the developer mentions it in the wiki Developer Notes "I adopted the login dialog style (no "Login button") to the challenge dialog. Shall there be a "Press Enter" hint?". Did Nextcloud remove the Login button at some point too? It seems to be there on Nextcloud 22, so they must have added it back. It seems like this is one of those changes for a new minimalist trend, but this is just silly when you remove a functional button completely and leave the person to only be able to continue by hitting Enter.

**Comment by wokawoka** [comment]
Yes, I also have all the users complaining that they couldn´t login.
Personally I've never stepped into a contact form without any submit button before. 
Amd it's also bad on mobile, like you said.
It would be great to revert back to the icon, like, If I've understood correctly, nextcloud did

**Comment by nursoda** [comment]
Hi guys, thanks for the heads up and sorry for the delay – my notifications were misconfigured by accident…

Yes, (1) the change was on purpose, (2) I followed the NC login (3) there at least was a time the login had no button (4) it has it back now. So I assume they received the same kind of flames ;)

I'll revert the change once I release a new version. It may take a while (at least until first NC24 betas are out) to package and publish it.

**Comment by nursoda** [comment]
This is what it looks like after applying the PR:

![image](https://user-images.githubusercontent.com/8425483/155902557-4f64a94b-18c2-4bfd-9fd7-8e6ce39e4bd0.png)

**Comment by wokawoka** [comment]
I also had a problem with github notifications and I've missed your reply.
The new version looks great, good choice. I'm looking forward to updating to your last version.
Thank you

**Comment by wokawoka** [comment]
I had to update nextcloud and the installation also automatically updated the Two-Factor Email app. Now the icon to fill in the code is again missing :(
I can't go back to the old version and as from tomorrow my users will complain again...

Do you have any plan to release the version you posted [here](https://github.com/nursoda/twofactor_email/issues/262#issuecomment-1053703702) n February?

Thank you very much again!

**Comment by nursoda** [comment]
I advise you to roll back to the last app version you had installed. All released apps still are available via GitHub.

I currently cannot release an update due to broken vue dependencies. If anyone is willing to help out fixing those, I'll be happy to release this weekend. Pleas PM me if you have some experience with vue 2->3 migration.

**Comment by wokawoka** [comment]
@nursoda
Thank you for your reply.

I'll try to manually install to an older app version by downloading it from github.
Do you  by chance remember which was the last version that was including the send icon? I'm not sure between v2.0.0 and v2.0.1.

I would be really glad to help but unfortunately I don´t have any experience with vue, I just hope someone else could help. Btw, shouldn´t this issue be open (since the new version is not yet released)?  It shows as closed at the moment.

Thank you very much for your work!

**Comment by nursoda** [comment]
2.0.1 should do.

**Comment by wokawoka** [comment]
> 2.0.1 should do.
Thank you! I will try to install the old version as soon as possible

**Comment by andyxheli** [comment]
@nursoda can we use 2.0.1 with NC 23 ?

**Comment by nursoda** [comment]
Yes. But 2.2.0 is in final testing, too 🎉

**Comment by nursoda** [comment]
2.2.0 published on GitHub and in App Store. Please reopen if it doesn't work as expected.

**Comment by andyxheli** [comment]
Just tested looks good no issues from my end :) thank you

**Comment by wokawoka** [comment]
@nursoda It works perfectly. Thank you so much!
