### ISSUE TITLE
Feature request: Force 2fa for all users but have an option to exclude specific groups

### ISSUE THREAD

**Issue by Jones-DE** [nursoda/twofactor_email#347]
Hi,

in our case we need to be able to force 2fa to all users but to also have the option to exclude specific groups. Nextcloud does the same with their implemented 2fa. 

Why force 2fa to all:
When dealing with large environments you will always have internal policies and local laws enforcing companies to implenent security features. If you have 14000 users you can be sure that only half of them will enable 2fa by their own. Most of them will just ignore the 2fa and the rest won't even know it's there. The only solution to ensure that everyone is using it is by giving administrators the option to force it to everyone.

Why exlude specific groups:
We are running a large NC environment serving 14000 Enterprise Users. Not all of them are "real" users / persons. About 90% of all users are read from active directory using LDAP but not all of them have an emailaddress / Exchange Mailbox. That's because we also use service accounts from within AD which are used to export and import data from SAP into Nextcloud and then back again from Nextcloud into other subsystems on other locations. Because all the automation and syhconization is done in the background there is no one logging into NC manually - that's where the exclude groups feature would really help.

Regards,
Jones

**Comment by nursoda** [comment]
I think that everything you ask for in your feature request already is available today from the basic 2FA infrastructure Nextcloud provides by the core package. This app only adds one more METHOD of 2FA (to be able to use an e-mail challenge as a second factor). The core functionality allows you to enforce ANY 2FA method – generally or for certain groups only, and allows you to exclude other groups from enforcement, see https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/two_factor-auth.html#enforcing-two-factor-authentication

Neither Nextcloud nor any Nextcloud 2FA app allows you to enforce a SPECIFIC 2FA method (such as twofactor_email), or to exclude a 2FA METHOD from enforcement. I will also not implement it since I think that the core functionality is suitable for all use cases I am aware of including yours. Some Nextcloud 2FA apps (inluding twofactor_email) currently lack support for INITIAL 2FA support. That is, to be able as a user to set up 2FA upon first logon after 2FA enforcement or user account creation. However, there already is an [issue](https://github.com/nursoda/twofactor_email/issues/35) for that, and a [pull request draft](https://github.com/nursoda/twofactor_email/pull/345) that would fix it.
