### ISSUE TITLE
NC25 APP icon not showing properly in dark mode

### ISSUE THREAD

**Issue by AndyXheli** [nursoda/twofactor_email#355]
![image](https://user-images.githubusercontent.com/59488153/189172334-be9ff55e-8597-450e-a875-540a152d820f.png)

**Comment by nursoda** [comment]
Already corrected in main. -> Next release.

**Comment by nursoda** [comment]
Not 100% sure: I cannot influence whether the icon in apps listing is shown as light/dark. If I set the app icon to light, then it's bad in light mode, if I set it to dark, then it's bad in dark mode. So I guess there's some unfinished theming changes. We should wait a bit, otherwise I'll discuss it at the nextcloud conference with staff.

**Comment by andyxheli** [comment]
Yea that don't sound right. Do you want me to leave this open ?

**Comment by nursoda** [comment]
No, I think that it's not to be fixed here, so "closed" is correct until I'm convinced otherwise in which case I'll reopen.

**Comment by andyxheli** [comment]
Hey @nursoda what do you think about this. shouldn't this fix our issue ? 

https://github.com/nextcloud/server/pull/33962/files

**Comment by nursoda** [comment]
If it is part oft beta5 then it didn't, see my forum post in beta5.

**Comment by andyxheli** [comment]
Yes i did see the comment on beta 5 this one is part of beta 6
