### ISSUE TITLE
how to disable twofactor_email

### ISSUE THREAD

**Issue by genloc** [nursoda/twofactor_email#368]
Hello all,
My predecessor built this 2FA into the cloud. I updated to version 27 last week and now the 2FA no longer works. I wanted to deactivate the 2FA, but the cloud now complains that min one of my 2FA could not be loaded. In the config it says 'twofactor_enforced' => 'false', but I think it belongs to another 2FA method. Does anyone know how I can completely disable the 2FA so that at least the users can access their data again? Unfortunately, deactivating the app leads to the error message.

Thank you very much for an answer.

**Comment by nursoda** [comment]
'twofactor_enforced' has nothing to do with twofactor_email, see [admin manual on 2FA](https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/two_factor-auth.html). You should investigate why 2FA no longer works. What issue(s) do you encounter? Are other twofactor_* apps installed? Do THEY work as expected? Did you / your users have BACKUP CODES generated? This is recommended and NC urges users to do so (see notifications the user gets in his/her environment).

To overcome temporary issues, you may use [Twofactor_Admin](https://apps.nextcloud.com/apps/twofactor_admin). You may also use OCC via console to [deactivate 2FA for single users](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#two-factor-auth-label).

Since you seem to have installed several NC versions upgrades: Are you sure your NC still can send E-Mails out? Have you tested that? If not, you might first want to fix that, and that's something way off topic for this app.

Since I have no other complaints with this app on NC27, I'll assume a configuration issue.
Since you contacted me by E-Mail directly, I'll close this issue as unrelated.
