### ISSUE TITLE
Nextcloud 29+30 Support

### ISSUE THREAD

**Issue by AndyXheli** [nursoda/twofactor_email#376]
Support for NC 29

**Comment by naelfe** [comment]
Yes please. Discovered it did not work when trying to log in after the update

**Comment by mmccarn** [comment]
I don't know if there is a reason for the delay.

[Info.xml](https://github.com/nursoda/twofactor_email/blob/v2/appinfo/info.xml) was updated with `<nextcloud min-version="24" max-version="29" />` on Mar 28 (but there have been no other changes since November...)

Two-Factor Email works for me if I force-enable it.

* Apps -> Disabled Apps
* "Allow Untested App"
* "Enable"

**Comment by nursoda** [comment]
I currently cannot build a Version that does not throw security warnings. I wait for an answer from Nextcloud.

If anyone can help out, please reach out!

I also had the app rebased on twofactor_TOTP, new version probably will be based on v3, available at https://github.com/datenschutz-individuell/twofactor_email

**Comment by pov91** [comment]
Are there any news, when a regular update is to be expected? 2FA is quite a standard these days, so Nextcloud should be interested in fixing the problem promptly. Thus, an update for a production system where users have set that is impossible.

**Comment by TheRaven500** [comment]
@nursoda: Who needs to be poked to get things moving? :smiley:

**Comment by nursoda** [comment]
Best would be if anyone with JS experience could offer me some time. Contact see olav.seyfarth.de

**Comment by pov91** [comment]
I hope you can find a helping hand. Thank you for taking care of the app. Is an important function. Unfortunately, I cannot help you.

**Comment by michal0202** [comment]
Any news on this topic?

**Comment by 42ske** [comment]
Is there any realistic estimation when we could expect the app to be running with NC 29?

**Comment by rdlab-upc** [comment]
Hello,

Fist of all thank you for the app, we know it is built and maintained by your own means.

@mmccarn [Info.xml](https://github.com/nursoda/twofactor_email/blob/v2/appinfo/info.xml) was updated with <nextcloud min-version="24" max-version="29" /> on Mar 28 (but there have been no other changes since November...)

Please, can you confirm this "workaround" still works on NC 29? Any issues/warnings?
Anyone else? @AndyXheli @naelfe @pov91 @michal0202 @42ske 
<br>

@nursoda I also had the app rebased on twofactor_TOTP, new version probably will be based on v3, available at https://github.com/datenschutz-individuell/twofactor_email   

Any estimation about it? AFAIK this code cannot be installed from the NC appstore and we will not dare to replace the pluging files.

<br>
Sadly we can only provide you IT infrastructure/admin support, programming is out of our expertise. Let us know if it can help you anyway.

<br>
Thank you.

**Comment by DazeEnd** [comment]
> I also had the app rebased on twofactor_TOTP, new version probably will be based on v3, available at https://github.com/datenschutz-individuell/twofactor_email

@rdlab-upc Are you saying that you have put together a version of twofactor_TOTP that sends the code by email instead of using TOTP? If that’s correct, I encourage you to contact the twofactor_TOTP team to share your work for possible long-term integration.

**Comment by rdlab-upc** [comment]
@DazeEnd We made some tests, unfortunately our integration was not  successful for v29 and we also care for collateral issues due the replacement of the original code.

That's why we ask for any advance in the v29/30 support.

**Comment by nursoda** [comment]
I apologize for the delay. I had a working version, but I broke it somehow. So, yes, there will be a version for v29+ soon. No promises on the day, but it will be shortly after the v30 release.

**Comment by bigcat88** [comment]
sorry for the spam, but is there any news on this?

**Comment by DazeEnd** [comment]
@nursoda I know this is a volunteer effort and you don’t owe anyone anything, but now that this issue is closed as “not planned”, can you provide a status update? Is this plugin not going to be updated? Is it effectively unmaintained? Or has this issue been superseded by another issue I missed? I just would like to be able to make a plan for upgrading.

In case it helps, I renew my offer of financial support if you are still needing to hire a developer to get this across the finish line.

**Comment by nursoda** [comment]
Dear Charles, thanks for offering that (again)! It's also good to hear that the app is used and users to care. I do feel bad for letting everyone down for so long (including my own instances, so I also do feel the urge. While I did try, life's had other plans with me.

Looking forward: This app is not dead, but this 'nursoda' repo will not see a version for NC >28. Development now is in https://github.com/datenschutz-individuell/twofactor_email/ This issue probably shouldn't have been just closed without comment but moved there.

Anyway: I'll contact you if I do need financial support. At the moment, it's rather lack of time.

**Comment by Zottel92** [comment]
@nursoda Thank you for your efforts to bring this forward and providing this important feature.
Maybe it would make sense to pin this closed issue here.
That would make it more clear for future readers that this Repo will be migrated.

**Comment by lightonflux** [comment]
Thanks for the clear communication @nursoda, I too suggest pinning this issue and archiving this repo, to improve the messaging about the state of this repo. Thanks for your work on the app and all the best for your future!
