### ISSUE TITLE
Push the button "Enable" doesn't work

### ISSUE THREAD

**Issue by gumaol** [nursoda/twofactor_email#56]
Email verification

The server can send authentication codes to your email address.
You are not using Email as a two-factor authentication method at the moment. "Enable"

I push the button "enable", but it did not function! No 2FA email would be send!

**Comment by andyxheli** [comment]
How are you relaying your email what server address are you using ? Meaning are you using google relay and putting in a fake email account ?

**Comment by JonOfUs** [comment]
I had the same problem, in the logs I found out that sending the email didn't work. The problem was a configuration change in my email account, so I had to correct my SMTP settings in the 'Basic Settings'. After this, everything worked fine. Maybe you could check whether your Email account is correctly configured.

Considering this, an error message describing what went wrong would be nice like 'Verification email could not be sent, please contact your admin to check settings'.

**Comment by nursoda** [comment]
I don't think that an app should try to find out WHY a mail cannot be sent. Probably the notification should contain something like "Inform your admin" but to be honest: I expect the server admin (either a "real" admin, or the single home user herself/himself) to care for that since there are LOTS of things depending on a working email setup. While I agree that twofactor_EMAIL has a somewhat closer relation to email, I still don't think that code trying to find out and display a cause should be part of this app.
